spring:
  application:
    # 应用名
    name: godmars-web

server:
  # 端口
  port: 30001

eureka:
  client:
    # 注册
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/

feign:
  hystrix:
    # 开启hystrix
    enabled: true

godmars-service:
  ribbon:
    # ribbon负载均衡策略改为轮训
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule